[tool.poetry]
name = "ledgertools"
version = "0.1.0"
description = "Ledger Tools"
authors = ["John Mee <git.commit@johnmee.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.4"
PyYAML = "^5.4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
